<?php
/**
 * Sea-Port Recommendation System
 *
 * @category   Application_Core
 * @package    seaport-recommender
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    seaport-recommender
 */
?>

<style type="text/css">
form#calculate_form dt {display: block;}    
</style>

<?php
$properPortName = $this->properPortName;
$properPortScore = $this->properPortScore;
$shipTotalWeights = $this->shipTotalWeights;
$shipWeightRandom = $this->shipWeightRandom;
$menu = array('menu' => 'admin_top_menu');
echo $this->topMenuWidget(array('headtitle' => 'Dashboard', 'menu' => $menu));
?>

<?php if(!isset($shipTotalWeights) || !count($shipTotalWeights)){ ?>
<div id="formholder">
    <h4>
        <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
        <?php echo $this->translate('Application Dashboard [Calculate Sea-Port for Vessel]'); ?>
    </h4>

    <div style="clear: both;"><br /></div>

    <div class="span add-company-form" style="margin-left: 0px;">
        <?php echo $this->form->render($this); ?>
    </div>
    <div style="clear: both;"></div>
</div>

<script type="text/javascript">
    $('#submit').prepend("<i class='icon-plus-sign icon-white'></i> ");
</script>
<?php }else{ ?>
<div class="company-list span" style="margin-left: 0px;">
    <h3 style="color: green;">
        <?php echo $this->translate('Best Port is - %s%s%s, Highest Score is - %s%s%s',
                '<span style="color: red;">', $properPortName, '</span>', '<span style="color: red;">', $properPortScore, '</span>'); ?>
    </h3>
    
    <div style="margin: 35px 0px;">
        <?php echo $this->chartPerShipWidget($shipWeightRandom, 'My Ship', 1, false); ?>
    </div>
    
    <table class="list-table table table-bordered table-hover">
        <thead>
            <tr style="background-color: #eee;">
                <th style="width: 300px;"><?php echo $this->translate('Sea-Port Name'); ?></th>
                <th style="width: 100px;"><?php echo $this->translate('Score Per Port'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($shipTotalWeights as $portName => $portScore): ?>
                <tr>
                    <td><?php echo ucwords($this->translate($portName)); ?></td>                   
                    <td><?php echo $portScore; ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php } ?>