<?php
/**
 * Sea-Port Recommendation System
 *
 * @category   Application_Core
 * @package    seaport-recommender
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    seaport-recommender
 */
?>

<style type="text/css">
    form#filter_form label {display: none;}
    .pagination {margin-top: 0px;}
    .custsubnav > li {text-align: left;}
    .btn-group > ul.dropdown-menu:before {
        border-bottom: 7px solid rgba(0, 0, 0, 0.2);
        border-left: 7px solid rgba(0, 0, 0, 0);
        border-right: 7px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 134px;
        position: absolute;
        top: -7px;
    }
    .btn-group > ul.dropdown-menu:after {
        border-bottom: 6px solid #FFFFFF;
        border-left: 6px solid rgba(0, 0, 0, 0);
        border-right: 6px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 135px;
        position: absolute;
        top: -6px;
    }
    @media (max-width: 980px) {
        .custresclass {
            float: none !important;
        }
    }
</style>

<?php
     $menu = array('menu' => 'admin_top_menu');
     echo $this->topMenuWidget(array('headtitle' => 'Admin', 'menu' => $menu));
?>

<h4>
     <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
     <?php echo $this->translate('Admin Panel [Sea-Port Information List]'); ?>
</h4>

<div style="clear: both;"></div>

<div class="span item_results" style="margin-left: 0px;">
  <div class="item-found">
    <?php $count = $this->paginator->getTotalItemCount(); ?>
    <?php
        if($count==1){
            echo $this->translate('Total %s sea-port found.', $count);
        }else{
            echo $this->translate('Total %s sea-ports found.', $count);
        }
    ?>
      <div class="btn-toolbar custresclass" style="float: right;">
          <div class="btn-group">
              <a href="<?php echo $this->url(array('action' => 'upload'), 'admin_port_general', true); ?>" class="btn">
                  <i class="icon-plus-sign"></i>
                  <?php echo $this->translate('Upload Sea-Port Data'); ?>
              </a>
              <a href="<?php echo $this->url(array('action' => 'calculate'), 'admin_port_general', true); ?>" class="btn">
                  <i class="icon-tasks"></i>
                  <?php echo $this->translate('Calculate Sea-Port'); ?>
              </a>
              <a href="javascript:void(0)" class="btn" id="deleteSelected">
                  <i class="icon-trash"></i>
                  <?php echo $this->translate('Delete Sea-Port Data'); ?>
              </a>
          </div>
      </div>
  </div>
  <?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
      <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array()); ?>
      </div>
  <?php endif; ?>
</div>

<?php if(count($this->paginator)): ?>
<div class="company-list span" style="margin-left: 0px;">
    <table class="list-table table table-bordered table-hover">
        <thead>
            <tr style="background-color: #eee;">
                <th><?php echo $this->translate('List of Sea Ports'); ?></th>
                <?php foreach($this->decisionCriteria as $criteria): ?>
                <th><?php echo ucwords($this->translate(str_replace("_", " ", $criteria))); ?></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->paginator as $portName => $portData): ?>
                <tr>
                    <td style="font-weight: bold; background-color: #eee;"><?php echo ucwords($this->translate($portName)); ?></td>
                    <?php foreach($portData as $port): ?>
                        <td><?php echo $port; ?></td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
    <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array()); ?>
    </div>
<?php endif; ?>

<script type="text/javascript">
$('#deleteSelected').click(function(){
    if(confirm('<?php echo $this->translate('Are you sure to delete port data?'); ?>')){
        location.href = "<?php echo $this->url(array('action' => 'delete'), 'admin_port_general', true); ?>";
    }
});
</script>
