<?php
/**
 * Sea-Port Recommendation System
 *
 * @category   Application_Core
 * @package    seaport-recommender
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    seaport-recommender
 */
?>

<style type="text/css">
form#upload_port dt {display: block;}    
</style>

<?php
$menu = array('menu' => 'admin_top_menu');
echo $this->topMenuWidget(array('headtitle' => 'Admin', 'menu' => $menu));
?>

<div id="formholder">
    <h4>
        <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
        <?php echo $this->translate('Admin Panel [Upload Sea-Port Data]'); ?>
    </h4>

    <div style="clear: both;"><br /></div>

    <div class="span add-company-form" style="margin-left: 0px;">
        <?php echo $this->form->render($this); ?>
    </div>
    <div style="clear: both;"></div>
</div>

<script type="text/javascript">
    $('#submit').prepend("<i class='icon-plus-sign icon-white'></i> ");
</script>
